on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.x'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pydantic
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Render Keymap
        run: |
          mkdir svg
          python draw.py keymaps/3x5+2.yaml > svg/3x5+2.svg
      - name: Archive
        uses: actions/upload-artifact@v2
        with:
          name: keymap
          path: svg/3x5+2.svg

